// to add:
// corpse looting
// bad habits
// broken bodies
// terrible traits
// random encounters/ varied by regions

const generateButton = document.getElementById("generate-button");
const nameDisplay = document.getElementById("name-display");
const categoryPicker = document.getElementById("kategoria");
const numberPicker = document.getElementById("liczba");

categoryPicker.addEventListener("change", (e) => {
  category = categoryPicker.value;
});

numberPicker.addEventListener("change", (e) => {
  numberGenerated = numberPicker.value;
});

let numberGenerated = 1;
let category = "MBNames";

const MBNames = {
  type: "mixer",
  prefix: [
    "Al",
    "Adal",
    "The",
    "Tor",
    "Tö",
    "Ur",
    "Dru",
    "Vik",
    "Va",
    "Vo",
    "Vra",
    "Vre",
    "We",
    "Ske",
    "Bur",
    "Burd",
    "Jau",
    "Ja",
    "Thro",
    "Tar",
    "Yv",
    "Gre",
    "Li",
    "Ga",
    "Or",
    "Mor",
    "Fe",
    "Wak",
    "Sun",
    "Gra",
    "Kran",
    "Kra",
    "Gne",
    "Kluv",
    "Qift-",
    "Mar",
    "Klo",
    "Dö",
    "Aerg-",
    "Ag",
    "Schlef",
    "Schle",
    "Bel",
    "Dom",
    "Vük",
    "Vü",
    "Bör",
    "Dae",
    "Kath",
    "Fel",
    "Got",
    "Sen",
    "Gri",
    "Haer",
    "Har",
    "Jot",
    "Kar",
    "Kat",
    "Kef",
    "Ku",
    "Kve",
    "Ly",
    "Mer",
    "Nag",
    "Ni",
    "Nif",
    "Prü",
    "Qill",
    "Ri",
    "Svi",
    "Illalukt",
    "Näs",
    "Kjell",
    "Mod",
    "Mund",
    "Eggar",
    "Ulf",
    "Som",
    "Göd",
    "Ärn",
    "Ödh",
    "Ærn",
    "Ylia",
    "Odhen",
    "Pe",
    "Orm",
    "Folk",
    "Gerul",
    "Det",
    "Le",
    "Ra",
    "An",
    "Les",
    "Josil",
    "Sig",
    "Sagso",
    "Hon",
    "Bon",
  ],
  suffix: [
    "ras",
    "fa",
    "rg",
    "vul",
    "rn",
    "m",
    "gel",
    "gal",
    "tan",
    "n",
    "kh",
    "si",
    "tor",
    "mut",
    "lh",
    "der",
    "er",
    "rk",
    "urk",
    "vl",
    "tuk",
    "kin",
    "til",
    "lt",
    "en",
    "gar",
    "gan",
    "ta",
    "ust",
    "vuld",
    "ngel",
    "gul",
    "th",
    "rist",
    "mol",
    "dul",
    "van",
    "lun",
    "tval",
    "zum",
    "sum",
    "kan",
    "buth",
    "kkan",
    "da",
    "ru",
    "an",
    "ban",
    "vel",
    "kil",
    "ttr",
    "rü",
    "gha",
    "mug",
    "na",
    "g",
    "la",
    "tar",
    "rt",
    "tz",
    "tin",
    "kari",
    "l",
    "duk",
    "uk",
    "ehl",
    "nach",
    "sten",
    "nd",
    "ande",
    "sig",
    "biorn",
    "u",
    "her",
    "gärdh",
    "dus",
    "ger",
    "mar",
    "ika",
    "gun",
    "dis",
    "karl",
    "lög",
    "biörn",
    "phus",
    "don",
    "dona",
    "on",
    "chela",
    "dy",
    "bert",
    "berta",
    "fúm",
    "ker",
  ],
};

const MBTowns = {
  type: "mixer",
  prefix: [
    "Alli",
    "Galgen",
    "Schles",
    "Ker",
    "On",
    "Gro",
    "Tor",
    "Skar",
    "Stur",
    "Draken",
    "Ebel",
    "Kal",
    "Breid",
    "Laug",
    "Ravn",
    "Esse",
    "Ful",
    "Hul",
    "Sten",
    "Kale",
    "Kirke",
    "Kirk",
    "Kli",
    "Langa",
    "Lund",
    "Akra",
    "Sand",
    "Alb",
    "Al",
    "Alt",
    "Amor",
    "Creuz",
    "Arn",
    "Aren",
    "Arz",
    "Auer",
    "Wind",
    "Bel",
    "Ber",
    "Berg",
    "Bergen",
    "Dürre",
    "Dürk",
    "Brücke",
    "Freien",
    "Staffel",
    "Borgen",
    "Baier",
    "Hers",
    "Bremer",
    "Breu",
    "Bra",
    "Bor",
    "Bott",
    "Born",
    "Braun",
    "Blanken",
    "Falken",
    "Clin",
    "Da",
    "Die",
    "Dür",
    "Dül",
    "Düssel",
    "Ehren",
    "Eckart",
    "Eber",
    "Enger",
    "Enne",
    "Eppel",
    "Eus",
    "Esch",
    "Filder",
    "Franken",
    "Frönden",
    "Fürsten",
    "Füs",
    "Füssen",
    "Furt",
    "Frank",
    "Gammer",
    "Gail",
    "Geisel",
    "Gel",
    "Geld",
    "Glau",
    "Gerolz",
    "Grün",
    "Güglin",
    "Glad",
    "Greven",
    "Grö",
    "Hagen",
    "Hada",
    "Halden",
    "Haldens",
    "Held",
    "Helm",
    "Hirsch",
    "Hochen",
    "Havel",
    "Heidel",
    "Hun",
    "Ingol",
    "Kalten",
    "Karben",
    "Karl",
    "Kir",
    "Kraut",
    "Krani",
    "Kon",
    "Kupfer",
    "König",
    "Kempt",
    "Kempt",
    "Kelster",
    "Kelk",
    "Kuppen",
    "Langa",
    "Leuten",
    "Lü",
    "Litchen",
    "Lauen",
    "Lange",
    "Lauf",
    "Linden",
    "Lüt",
    "Mans",
    "Mitten",
    "Min",
    "Markt",
    "Mühlen",
    "Mon",
    "Münche",
    "Mun",
    "Neuen",
    "Neu",
    "Nieder",
    "Nieden",
    "Nort",
    "Nitten",
    "Nier",
    "Nien",
    "Nord",
    "Ober",
    "Oberz",
    "Oster",
    "Osten",
    "Oppen",
    "Olden",
    "Orn",
    "Orten",
    "Oder",
    "Pfung",
    "Rabe",
    "Rade",
    "Rends",
    "Rasten",
    "Rie",
    "Roten",
    "Rein",
    "Schau",
    "Stadt",
    "Schram",
    "Schrap",
    "Stein",
    "Teu",
    "Tete",
    "Taun",
    "Tan",
    "Traun",
    "Uffen",
    "Un",
    "Ummer",
    "Vel",
    "Vils",
    "Vissel",
    "Voh",
    "Vre",
    "Volk",
    "Volks",
    "Volker",
    "Wald",
    "Witten",
    "Wissen",
    "Winter",
    "Wermel",
    "Wern",
    "Witt",
    "Wein",
    "Wermel",
    "Wals",
    "Wolfem",
    "Wol",
    "Wolken",
    "Wurz",
    "Wasser",
    "Ziegen",
    "Zeren",
    "Zirn",
    "Zitt",
    "Zwingen",
    "Zwei",
    "Zei",
    "Goblin",
    "Lusi",
    "Arkh",
    "Gorgh",
    "Gorghen",
    "Arkhen",
    "Lusen",
    "Verhu",
    "Verhen",
    "Chrypt",
    "Chrypten",
    "Josil",
    "Josilf",
    "Grav",
    "Grift",
    "Griften",
    "Sigfúm",
    "Anthelia",
    "Fathmu",
    "Aldon"
  ],
  suffix: [
    "ans",
    "beck",
    "wig",
    "güs",
    "da",
    "vi",
    "por",
    "de",
    "la",
    "toft",
    "brek",
    "dal",
    "by",
    "gard",
    "garde",
    "hus",
    "kot",
    "bo",
    "nes",
    "vik",
    "sun",
    "torp",
    "berg",
    "heim",
    "dorf",
    "haus",
    "stadt",
    "stedt",
    "feld",
    "leben",
    "steig",
    "kirchen",
    "bach",
    "burg",
    "helm",
    "zig",
    "ka",
    "nau",
    "walde",
    "stein",
    "haven",
    "vörde",
    "kel",
    "kum",
    "rom",
    "schweig",
    "schau",
    "gen",
    "un",
    "shagen",
    "men",
    "en",
    "thal",
    "sen ",
    "wangen",
    "furt",
    "men",
    "münden",
    "chau",
    "broich",
    "mühlen",
    "ditz",
    "enau",
    "mar",
    "stel",
    "stanz",
    "ten",
    "dau",
    "zen",
    "den",
    "schau",
    "ster",
    "sulm",
    "rade",
    "mark",
    "kloster",
    "horn",
    "lau",
    "den",
    "borg",
    "a",
    "ia",
    "um",
    "glo",
    "blod",
    "blud"
  ],
};

const MBWeather = {
  type: "picker",
  list: [
    "Martwa szarość",
    "Walący deszcz",
    "Przeszywający wiatr",
    "Ogłuszająca burza",
    "Ciemno jak w nocy",
    "Martwa cisza",
    "Urwanie chmury",
    "Mgła gęsta jak zupa",
    "Trzaskający mróz",
    "Irytująca mżawka",
    "Warczące grzmoty",
    "Grobowe zimno",
  ],
};

const MBCorpseLoot = {
  type: "picker",
  list: [
    "k4 w srebrze",
    "k6 w srebrze",
    "k8 w srebrze",
    "k10 w srebrze",
    "k20 w srebrze",
    "k20 w srebrze",
    "k20 (eksplodujące) w srebrze",
    "k20 w srebrze",
    "k20 w srebrze",
    "k20 w srebrze",
    "k20 w srebrze",
    "k20 w srebrze",
    "k20 w srebrze",
    "k66 w srebrze",
    "k66 w srebrze",
    "k66 w srebrze",
    "k100 w srebrze",
    "Garnuszek z niesamowicie skuteczną maścią wywołującą swędzenie",
    "Naszyjnik z ludzkich zębów",
    "Worek wściekłych, jadowitych ciem, DR6 na Twardość albo śmierć",
    "Kieszeń pełna popękanego szkła, k2 obrażeń",
    "Szalony manifest, jeśli go przeczytasz, rzuć DR12 na Prezencję, w przypadku porażki jesteś tak zmieszany, że tracisz na stałe 1 pkt prezencji",
    "Klucz do pobliskich drzwi, kradziony",
    "Mapa domu zamożnej, choć słabej rodziny",
    "Zadziwiająca ilość pająków (martwych)",
    "Zadziwiająca ilość pająków (żywych)",
    "Zadziwiająca ilość szczurów (martwych)",
    "Zadziwiająca ilość szczurów (żywych)",
    "Metalowy cylinder wypełnionych prochem, z lontem. 1-2 tracisz rękę, 3-6 zadaje 3k10 obrażeń tam, gdzie wyląduje.",
    "Twarz znanego i znienawidzonego łowcy czarownic",
    "Twarz znanego i lubianego łowcy czarownic",
    "Kartka z listą imion Bohaterów Graczy, jedno z imion jest skreślone",
    "Umęczona wróżka z urwanymi skrzydełkami i wyłupionymi oczami",
    "Mapa do miejsca, które nie ma prawa istnieć",
    "Nieoznakowana butelka z cieczą, która mieni się raz czerwono, raz na zielono",
    "Papier dłużny, lokalny potentat jest winny posiadaczowi znaczną sumę pieniędzy.",
    '"Woda życia", leczy k8, test twardości DR10 albo ślepniesz. Wysoce alkoholowa.',
    "Maska pośmiertna jednego z BG",
    "Z tym coś było ewidentnie nie tak. Ręce ma pokryte czymś ciepławym, brązowym i mocno kwasowym. K2+1 obrażeń i okropnie śmierdzisz przez k4 dni.",
    "Czarny sztylet z Kergus, 2k4 obrażeń",
    "Podpisana buteleczka z trucizną, test DR12 na twardość, albo losowy atrybut spada o k4.",
    "Skalp z długimi czarnymi włosami",
    "Złota kula z niewidzialnym łączeniem, otwierana wykręcaniem",
    "Zakrwawiony kastet",
    "Dwie obciążone kości.",
    "Puchar z czaszki jakiegoś nieszczęśnika",
    "Wisiorek z ususzonej krowiej głowy wiszącej do góry nogami na rzemyku",
    "Zestaw kart tarota, dwóch brakuje.",
    "Woreczek z bladozielonymi ziołami (herbata, daje sen bez marzeń, ale redukuje prezencję o 1 następnego dnia 2k6 porcji)",
    "Żelazna obroża.",
    "Zakorkowana flaszka z bardzo silnym alkoholem",
    "Osełka",
    "Drewniana łyżka",
    "Medalion z lokiem rudych włosów.",
    "List gończy, poszukiwany winny rabunku i kradzieży, 50s żywy, 10s martwy",
    "Pierścionek z fałszywym klejnotem, skrywającym dawkę czarnej trucizny.",
    "Szmaciana lalka",
    "Puzderko z uschniętym, gnijącym palcem od stopy należącym do zwłok, ma wczesne stadium trądu.",
    "Słoik z usychającą ropuchą, niewypuszczona zginie w ciągu k4 dni",
    "Gwizdek",
    "Suszony penis trolla",
    "Małe lusterko",
    "Łuska wielkości dłoni",
    "Złoty ząb (ma go w ustach)",
    "Srebrny medalion z wizerunkiem bazyliszka",
    "Mała szklana fiolka z laudanum",
    "Zasuszone serce",
    "Mała figurka anioła, ułamane skrzydło",
    "Złota moneta z wybitą na niej czaszką",
    "Brzytwa",
    "Fiolka Elixiru Vitalis, jedna dawka",
    "Malutki klejnot, schowany w bucie, wart 10+2k6 s",
    "Naszyjnik ze srebrnym krzyżykiem",
    "Teleskopowa luneta",
    "Kawałek suszonej ludzkiej skóry z wytatuowanym tekstem (przeklęty zwój)",
    "Resztki czegoś bezwartościowego rozsypują się w twoich rękach",
    'Kilka zgniłych jabłek.',
'Czaszki.',
'Dwie zakrwawione pochodnie.',
'Grzebień z pojedyńczym siwym włosem.',
'Flet (smakuje okropnie).',
'Mała buteleczka wypełniona krwią.',
'Ćwiekowany skórzany naramiennik.',
'Połamana porcelanowa lalka.',
'Kawałek spleśniałego chleba.',
'Martwy czarny kot.',
'Wędka z zardzewiałym haczykiem.',
'Długi stryczek',
'Czerwony kaptur i maska.',
'Mały drewniany kuferek (pusty)',
'k8 kolorowych szklanych kulek.',
'Rakieta śnieżna (zamieszkana przez pająka).',
'Olejny obraz zakapturzonego szkieleta.',
'Wachlarz w kształcie niedźwiedziego szponu.',
'Kunsztowna jedwabna rękawiczka',
'Suszone mięso nietoperza.'

  ],
};

const wizardNames = {
  type: "picker",
  list: [
    "Venalex",
    "Furagina",
    "Dicoflor",
    "Narivent",
    "Ibuprofen",
    "Paracetamol",
    "Sinecod",
    "Sirdalud",
    "Dicortineff",
    "Folik",
    "Propolis",
    "Aspargin",
    "Magnefar",
    "Neosine",
    "Sanostol",
    "Prospan",
    "Hederasal",
    "Herdripsan",
    "Tasectan",
    "Biofenac",
    "Berodual",
    "Fluconazol",
    "Efferalgan",
    "Diclofenac",
    "Fenistil",
    "Betahistyna",
    "Cortineff",
    "Baclofen",
    "Codeina",
    "Gynalgin",
    "Acodin",
    "Borasol"
  ]

}

function removeAllChildren(element) {
  let counter = element.children.length;
  for (let m = 0; m <= counter; m++) {
    if (element.children[0]) {
      element.children[0].remove();
    }
  }
}

function randomizeFromArray(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function displayArray(ar, parent) {
  for (j = 0; j < ar.length; j++) {
    let line = document.createElement("p");
    line.innerText = ar[j];
    parent.appendChild(line);
  }
}

generateButton.addEventListener("click", () => {
  let result = [];
  console.log(category);
  console.log(eval(category));
  let pickedCategory = eval(category);
  removeAllChildren(nameDisplay);
  for (let i = 0; i < numberGenerated; i++) {
    if (pickedCategory.type === "mixer")
      result.push(
        randomizeFromArray(pickedCategory.prefix) +
          randomizeFromArray(pickedCategory.suffix)
      );
    else if (pickedCategory.type === "picker") {
      result.push(randomizeFromArray(pickedCategory.list));
    }
  }
  displayArray(result, nameDisplay);
});
